@startuml Proyecto

class Actualizable
class Corredor
class Dibujo
class Rampa
class Ventana

Dibujo-|>Actualizable
Corredor-|>Dibujo
Rampa-|>Dibujo
Ventana o--Actualizable
Corredor-|>Actualizable
Rampa-|>Actualizable
Ventana o--Dibujo
Corredor o--Rampa
Ventana*--Corredor
Ventana*--Rampa

@enduml